// console.log("data")
const fs=require("fs")
fs.writeFileSync("sample3.txt","data")
fs.appendFileSync("sample3.txt","new data")
fs.readFileSync("sample3.txt")
const data=fs.readFileSync("sample3.txt","utf-8")
console.log(data)
const new1=data.toString()
console.log(data)